
services:
  app:
    build:
      context: .
      dockerfile: RateLimiter.SlidingWindowPractice/Dockerfile
    container_name: rate-limit-app
    depends_on:
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Redis: "redis:6379"
    ports:
      - "5000:8080"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    restart: always
    ports:
      - "8001:8001" 

volumes:
  redis_data: